### ISSUE TITLE
Error trying to run parallel louvain implementation

### ISSUE THREAD

**Issue by willi3by** [wweir827/CHAMP#6]
Hi, 

I am attempting to run the tutorial code under Partition Ensemble Example but when I try to run the champ.parallel_louvain command, I get this error message:

Traceback (most recent call last):

  File "<ipython-input-4-d46595ebb914>", line 5, in <module>
    progress=True)

  File "/Users/wilxl8/anaconda3/lib/python3.6/site-packages/champ/louvain_ext.py", line 1337, in parallel_louvain
    parts_list_of_list=pool.map(_run_louvain_parallel, parallel_args )

  File "/Users/wilxl8/anaconda3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "/Users/wilxl8/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

TypeError: find_partition() missing 1 required positional argument: 'partition_type'

I have tried to resolve the issue myself but can't seem to find the problem. Could you help me with this issue?

Thank you,
Brady Williamson

**Comment by willi3by** [comment]
Hi William, 

Thank you for the quick reply. Your suggestion fixed the problem! I uninstalled the version of champ I was using and installed from the source code on github and everything seems to be working great now. One nonsignificant issue, when I typed champ.version, I got the error that champ has no attribute called "version". No big deal, I just thought I would let you know. 

Thank you,
Brady

**Comment by willi3by** [comment]
Sorry, one additional question. When I try to plot the partitions, I am getting another error. I know the source of the problem but am not sure what to change in the code:
#My code is:
ens.plot_modularity_mapping(ax=a3,no_tex=False)

#And the error message is:
Traceback (most recent call last):

  File "<ipython-input-16-bafae1b887bf>", line 1, in <module>
    ens.plot_modularity_mapping(ax=a3,no_tex=False)

  File "/Users/wilxl8/anaconda3/lib/python3.6/site-packages/champ-1.0.7-py3.6.egg/champ/louvain_ext.py", line 1228, in plot_modularity_mapping
    champ_inds=self.get_CHAMP_indices()

  File "/Users/wilxl8/anaconda3/lib/python3.6/site-packages/champ-1.0.7-py3.6.egg/champ/louvain_ext.py", line 891, in get_CHAMP_indices
    inds.sort(key=lambda x: x[1])

AttributeError: 'zip' object has no attribute 'sort'

Thanks again,
Brady

**Comment by wweir827** [comment]
No problem at all.  Most of the testing was in python2 so there are definitely still some kinks.  I just pushed a couple of fixes.  I got same error and now its gone so should be good to go.  Please don't hesitate to let me know if anything else pops up.

**Comment by willi3by** [comment]
Great! Thank you very much again for your assistance.
